### ISSUE TITLE
Please add code for generating the input.csv  file.

### ISSUE THREAD

**Issue by aminrahimian** [aminrahimian/PA-election-map#1]
@LyanRy  With most of the online CSV files will have the option to download them directly using a command like read_csv. You can also scrape some of the files from the html source.

**Comment by LyanRy** [comment]
This is the sample csv file after electing the row of "ID number","Party Code", merge the address line to the new column named "address" and "Zip".
https://github.com/LyanRy/map-PA-voter/blob/main/ADAMS_party.csv
This is the file after geocoding and changing the party number except D and R to other
https://github.com/LyanRy/map-PA-voter/blob/main/add.csv
https://github.com/LyanRy/map-PA-voter/blob/main/new.csv

**Comment by aminrahimian** [comment]
Thanks for uploading the files. Please include links to the sources in the
comments (online links to download the source files)
